name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: IDF v5.3.2 / esp32s3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.2
          target: esp32s3
          path: "."
          command: idf.py build
